version: "3"

services:
    jenkins-blueocean:
      build: 
        context: .
        dockerfile: Dockerfile
      environment: 
        - DOCKER_HOST=tcp://docker:2376
        - DOCKER_CERT_PATH=/certs/client
        - DOCKER_TLS_VERIFY=1
      volumes: 
        - type: volume
          source: jenkins-docker-certs
          target: /certs/client
        - type: volume
          source: jenkins-data
          target: /var/jenkins_home
      ports:
        - "8080:8080"
        - "5000:5000"
      
    jenkins-docker:
      image: docker:dind
      privileged: true
      volumes: 
        - type: volume
          source: jenkins-docker-certs
          target: /certs/client
        - type: volume
          source: jenkins-data
          target: /var/jenkins_home
      environment: 
        - DOCKER_TLS_CERTDIR=/certs
      ports: 
        - "2376:2376"
      command: --storage-driver=overlay2
volumes: 
  jenkins-docker-certs: 
  jenkins-data: 