name: Continuous Integration
on: [push] # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        dotnet: [ '2.1.x', '3.1.x', '5.0.x' ]
        node: ['10', '12']
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
    
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
          with:
              dotnet-version: ${{ matrix.dotnet }}

      - name: Setup node
        uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node }}

      - name: Build C# code
        run: dotnet build

      - name: Test C# code
        run: dotnet test

      - name: npm install
        working-directory: ./DotnetTemplate.Web
        run: npm install

      - name: Linter
        working-directory: ./DotnetTemplate.Web
        run: npm run lint

      - name: npm test
        working-directory: ./DotnetTemplate.Web
        run: npm t
